---
sidebar: sidebar 
permalink: docs/task_nde_configure_net_settings.html 
summary: NetApp HCI 배포 네트워크 설정을 구성하는 방법에 대해 알아봅니다. 
keywords: netapp, hci, deployment, compatibility, nodes 
---
= 네트워크 설정을 구성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI는 네트워크 구성을 단순화하기 위한 쉬운 형식의 네트워크 설정 페이지를 제공합니다. Easy 양식을 작성하면 NetApp HCI가 네트워크 설정 페이지에 있는 나머지 정보 대부분을 자동으로 채웁니다. 그런 다음 계속하기 전에 최종 네트워크 설정을 입력하고 네트워크 구성이 올바른지 확인할 수 있습니다. 양식을 완전히 작성할 필요는 없습니다.

.필요한 것
* 다음 정보를 얻었다고 할 수 있습니다.
+
** 호스트 및 스토리지 클러스터에 대해 계획된 명명 접두사
** 관리, iSCSI 및 vMotion 네트워크의 모든 계획된 서브넷 마스크, 시작 IP 주소, 기본 게이트웨이 및 VLAN ID
** 계획된 VMware vCenter 구축을 위한 IP 주소, 기본 게이트웨이, VLAN ID 및 서브넷 마스크 정보입니다
** NetApp HCI의 NTP(네트워크 시간 프로토콜) 서버 주소입니다
** NetApp HCI에 대한 DNS 서버 IP 주소 정보입니다


* vSphere Distributed Switch를 구축하는 경우 구축이 완료된 후 vSphere Enterprise Plus 라이센스를 적용할 수 있습니다.
* TUI(터미널 사용자 인터페이스) 구성 중에 노드 포트에 VLAN ID를 할당한 경우 네트워크 구성 중에 해당 포트를 동일한 VLAN ID로 구성했습니다. 연결된 스위치 포트에서 태그가 지정된 호스트 포트를 액세스 포트 또는 기본 VLAN으로 구성할 필요가 없습니다.
* 네트워크 스위치 구성이 올바른지 확인했습니다. 잘못된 스위치 구성(예: 잘못된 VLAN 또는 MTU 크기)으로 인해 배포 오류가 발생합니다.


.이 작업에 대해
컴퓨팅 노드에 대해 케이블 2개로 구성된 네트워크 토폴로지를 선택한 경우 vMotion에 VLAN ID를 사용하고 구축 시 모든 컴퓨팅 및 스토리지 노드에 대해 스토리지 네트워크를 사용해야 합니다(VLAN ID는 관리 네트워크에서는 선택 사항).


NOTE: 구축 전에 호스트 측 VLAN 태그 지정이 필요한 환경에서 NetApp 배포 엔진에서 검색할 수 있도록 컴퓨팅 및 스토리지 노드에 VLAN ID를 구성한 경우, NetApp 배포 엔진에서 네트워크 설정을 구성할 때 올바른 VLAN을 사용해야 합니다.

2노드 또는 3노드 스토리지 클러스터를 사용하여 구축하는 경우 간편한 양식을 사용한 후 * Network Settings * 페이지에서 Witness Node에 대한 IP 주소 정보를 완료할 수 있습니다.

.단계
. 선택 사항: 이 페이지에 입력한 네트워크 정보의 실시간 유효성 검사를 비활성화하려면 * Live network validation is * switch * to * Off * 로 전환합니다.
. 네트워크 설정 * 페이지의 * 인프라 서비스 * 섹션에서 다음 필드에 NetApp HCI에 대한 DNS 및 NTP 서버 정보를 입력합니다.
+
|===
| 필드에 입력합니다 | 설명 


| * DNS 서버 IP 주소 1 * | NetApp HCI에 대한 기본 DNS 서버의 IP 주소입니다. vCenter 구성 페이지에서 DNS 서버를 지정한 경우 이 필드가 채워지고 읽기 전용입니다. 


| * DNS 서버 IP 주소 2(선택 사항) * | NetApp HCI용 보조 DNS 서버의 선택적 IP 주소입니다. 


| * NTP 서버 주소 1 * | 이 인프라에 대한 기본 NTP 서버의 IP 주소 또는 정규화된 도메인 이름입니다. 


| * NTP 서버 주소 2(선택 사항) * | 이 인프라에 대한 보조 NTP 서버의 선택적 IP 주소 또는 정규화된 도메인 이름입니다. 
|===
. 시간을 절약하려면 * 를 선택하고 간단한 양식 * 을 실행하여 네트워크 설정을 줄일 수 있습니다.
+
네트워크 설정 Easy Form * 대화 상자가 나타납니다.

. 이름 접두사 * 필드에 이름 지정 접두사를 입력합니다.
+
이름 접두사는 각 호스트의 이름과 스토리지 클러스터의 이름에 적용됩니다. 접두사의 이름 지정에는 다음과 같은 특성이 있습니다.

+
** 문자로 시작해야 합니다
** 문자, 숫자 및 하이픈을 포함할 수 있습니다
** 55자를 초과할 수 없습니다


. VLAN ID 할당에 대해 다음 옵션 중 하나를 선택합니다.
+
폼을 사용할 때 항상 행 옆에 있는 * Clear * 를 선택하여 필드 행에서 입력을 지웁니다.

+

NOTE: VLAN ID를 할당할 때 NetApp HCI가 네트워크 트래픽에 적용할 VLAN 태그를 구성합니다. 네이티브 VLAN을 VLAN ID로 입력할 필요가 없습니다. 네트워크에 네이티브 VLAN을 사용하려면 해당 필드를 비워 두십시오.

+
|===
| 옵션을 선택합니다 | 단계 


| VLAN ID를 할당합니다  a| 
.. VLAN ID * 를 할당하게 됩니다 * 옵션에 대해 * 예 * 를 선택합니다.
.. VLAN ID * 열에 VLAN에 할당할 각 네트워크 트래픽 유형에 사용할 VLAN 태그를 입력합니다.
+
컴퓨팅 vMotion 트래픽과 iSCSI 트래픽 모두 비공유 VLAN ID를 사용해야 합니다.

.. 다음 * 을 선택합니다.
.. 서브넷* 열에서 각 네트워크의 각 네트워크 트래픽 유형에 대해 CIDR 형식으로 서브넷 정의를 입력합니다(예: 192.168.1.0/24).
.. 기본 게이트웨이 * 열에서 각 네트워크의 각 네트워크 트래픽 유형에 대한 기본 게이트웨이의 IP 주소를 입력합니다.
.. 시작 IP * 열에 각 네트워크의 각 네트워크 서브넷에 대해 사용 가능한 첫 번째 IP 주소를 입력합니다.




| VLAN ID를 할당하지 마십시오  a| 
.. VLAN ID * 옵션을 * 지정 * 으로 * 아니요 * 를 선택합니다.
.. 서브넷* 열에서 각 네트워크의 각 네트워크 트래픽 유형에 대해 CIDR 형식으로 서브넷 정의를 입력합니다(예: 192.168.1.0/24).
.. 기본 게이트웨이 * 열에서 각 네트워크의 각 네트워크 트래픽 유형에 대한 기본 게이트웨이의 IP 주소를 입력합니다.
.. 시작 IP * 열에 각 네트워크의 각 네트워크 트래픽 유형에 대해 사용 가능한 첫 번째 IP 주소를 입력합니다.


|===
. 네트워크 설정에 적용 * 을 선택합니다.
. 예 * 를 선택하여 확인합니다.
+
이렇게 하면 * 네트워크 설정 * 페이지가 Easy 양식에 입력한 설정으로 채워집니다. NetApp HCI는 입력한 IP 주소의 유효성을 검사합니다. 라이브 네트워크 유효성 검사 사용 안 함 단추를 사용하여 이 유효성 검사를 비활성화할 수 있습니다.

. 자동으로 채워진 데이터가 올바른지 확인합니다.
. Continue * 를 선택합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI 리소스 페이지를 참조하십시오"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire 및 Element 소프트웨어 설명서 센터"^]

