---
sidebar: sidebar 
permalink: docs/task_mnode_enable_remote_support_connections.html 
summary: 관리 노드를 사용하여 문제 해결을 위해 NetApp Support 액세스를 설정할 수 있습니다. 
keywords: netapp, mnode, management node, connect to support, support tunnel, rst 
---
= 원격 NetApp 지원 세션을 시작합니다
:allow-uri-read: 


[role="lead"]
NetApp HCI 시스템에 대한 기술 지원이 필요한 경우 NetApp Support를 통해 시스템과 원격으로 연결할 수 있습니다. 세션을 시작하고 원격 액세스를 위해 NetApp Support는 사용자 환경에 대한 역방향 SSH(Secure Shell) 연결을 열 수 있습니다.

.이 작업에 대해
NetApp Support를 통해 SSH 역방향 터널 연결을 위한 TCP 포트를 열 수 있습니다. 이 연결을 통해 NetApp Support에서 관리 노드에 로그인할 수 있습니다. 관리 노드가 프록시 서버 뒤에 있는 경우 sshd.config 파일에 다음 TCP 포트가 필요합니다.

[cols="15,25,60"]
|===
| TCP 포트입니다 | 설명 | 연결 방향 


| 443 | 개방형 지원 터널을 통해 웹 UI로 역포트 포워딩을 위한 API 호출/HTTPS | 관리 노드에서 스토리지 노드로 


| 22 | SSH 로그인 액세스 | 관리 노드에서 스토리지 노드 또는 스토리지 노드에서 관리 노드로 
|===

NOTE: 기본적으로 원격 액세스 기능은 관리 노드에서 사용하도록 설정됩니다. 원격 액세스 기능을 비활성화하려면 를 참조하십시오link:task_mnode_ssh_management.html["관리 노드에서 SSH 기능을 관리합니다"]. 필요한 경우 원격 액세스 기능을 다시 활성화할 수 있습니다.

.단계
* 관리 노드에 로그인하고 터미널 세션을 엽니다.
* 프롬프트에서 다음을 입력합니다.
+
`rst -r  sfsupport.solidfire.com -u element -p <port_number>`

* 원격 지원 터널을 닫으려면 다음을 입력합니다.
+
`rst --killall`



[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

