---
sidebar: sidebar 
permalink: docs/task_nde_join_existing_vsphere.html 
summary: NetApp HCI 구축 중에 VMware vSphere를 구성하는 방법을 알아보십시오. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= 기존 VMware vSphere 구축 환경에 가입하십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter Server 네트워크 정보 및 자격 증명을 제공하여 기존 vSphere 구축을 활용하도록 NetApp HCI를 구성합니다.

.필요한 것
* 기존 vSphere 6.7 구축에 참여하는 경우 vCenter Server가 버전 6.7 업데이트 1을 실행 중인지 확인합니다.
* 기존 vSphere 6.5 배포에 참여하는 경우 vCenter Server에서 버전 6.5 업데이트 2 이상이 실행되고 있는지 확인합니다.
* 기존 vSphere 구축에 대한 네트워크 세부 정보 및 관리자 자격 증명을 얻습니다.


.이 작업에 대해
vCenter 연결 모드를 사용하여 연결된 여러 vCenter Server 시스템에 연결된 경우 NetApp HCI는 vCenter Server 시스템 중 하나만 인식합니다.


NOTE: NetApp Element Plug-in for vCenter Server를 사용하여 를 사용하여 다른 vCenter Server의 클러스터 리소스를 관리하는 link:https://docs.netapp.com/us-en/vcp/vcp_concept_linkedmode.html["vCenter 연결 모드"^]것은 로컬 스토리지 클러스터로만 제한됩니다.

.단계
. Join and extend a existing vSphere Deployment * 를 선택합니다.
. vCenter Server 도메인 이름 또는 IP 주소 * 필드에 도메인 이름 또는 IP 주소를 입력합니다. 도메인 이름을 입력하는 경우 표시되는 * DNS Server IP Address * 필드에 활성 DNS 서버의 IP 주소를 입력해야 합니다.
. 사용자 이름 및 암호 * 필드에 vSphere 관리자의 자격 증명을 입력합니다.
. Continue * 를 선택합니다.


[discrete]
== 자세한 내용을 확인하십시오

* link:firmware_driver_versions.html["NetApp HCI 스토리지 노드의 NetApp HCI 및 펌웨어 버전에 대해 지원되는 펌웨어 및 ESXi 드라이버 버전"]

