---
sidebar: sidebar 
permalink: docs/task_nde_disable_lacp_individual.html 
summary: 'NetApp HCI를 구축한 후 구성된 스위치에서 명령을 사용하지 않도록 설정하는 방법에 대해 `lacp-individual` 알아봅니다.' 
keywords: netapp, hci, deployment, review, deploy 
---
= 구성된 스위치에서 "LACP-Individual" 명령을 비활성화합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
기본적으로 Mellanox switch 명령과 Cisco `lacp suspend-individual` switch `lacp-individual` 명령은 구축 후 구성된 상태로 유지됩니다. 이 명령은 설치 후 필요하지 않습니다. 구성이 남아 있으면 스위치를 문제 해결하거나 재부팅할 때 볼륨 액세스 문제가 발생할 수 있습니다. 구축 후 각 Mellanox 스위치 및 Cisco 스위치 구성을 확인하고 또는 `lacp suspend-individual` 명령을 제거해야 `lacp-individual` 합니다.

.단계
. SSH를 사용하여 스위치에 대한 세션을 엽니다.
. 실행 중인 구성을 표시합니다.
+
`show running-config`

. 또는 `lacp suspend-individual` 명령의 스위치 구성 출력을 `lacp-individual` 확인합니다.
+

NOTE: 는 `xxx-xxx` 사용자가 제공한 인터페이스 번호입니다. 필요한 경우 다중 섀시 Link Aggregation Group 인터페이스를 표시하여 인터페이스 번호에 액세스할 수 있습니다. `show mlag interfaces`

+
.. Mellanox 스위치의 경우 출력에 다음 줄이 포함되어 있는지 확인합니다.
+
`interface mlag-port-channel xxx-xxx lacp-individual enable force`

.. Cisco 스위치의 경우 출력에 다음 줄이 포함되어 있는지 확인합니다.
+
`interface mlag-port-channel xxx-xxx lacp suspend-individual enable force`



. 명령이 있는 경우 구성에서 제거합니다.
+
.. Mellanox 스위치의 경우:
+
`no interface mlag-port-channel xxx-xxx lacp-individual enable force`

.. Cisco 스위치의 경우:
`no interface mlag-port-channel xxx-xxx lacp suspend-individual enable force`


. 구성의 각 스위치에 대해 이 단계를 반복합니다.


[discrete]
== 자세한 내용을 확인하십시오

* https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/SF_Series/SolidFire_Bond10G_goes_down_when_flapping_an_interface_during_troubleshooting["문제 해결 중에 스토리지 노드가 다운됩니다"^]

